Dimos/exclude families
BioGeMT/miRBench_paper pull request #45
Opened 2024-12-06 12:56 UTC by dimostzim

These scripts filter for unique miRNA families in one dataset (eg Manakov) compared to other 2 (eg Hejret, Klimentova) and split the original dataset (eg Manakov) into 2 (one with excluded miRNA families, one with all the rest)

2024-12-06 14:33 UTC, stephaniesamm commented on code/excluded_families_testset/exclude_fam.py
Can we rename `left_out` and `excluded` dfs and arguments because it is unclear which is which. 

From code I am assuming that `excluded` is the data that will be what we have been calling the "left out" or "unseen" test dataset, and `left_out` is the data that we will continue processing and split into train and test. Is this correct?

Mayb we can call them `left_out_unseen` and just `dataset` respectively?

2024-12-06 15:46 UTC, evaklimentova commented on code/excluded_families_testset/exclude_fam.py
I agree; this is also confusing for me. Let's at least stick to the `left_out` name for the ones that are not in any other dataset, excluded from the Manakov, and treated as a separate test set.

2024-12-06 15:46 UTC, evaklimentova commented on code/excluded_families_testset/unique_family_counter.py
> +   df1 = pd.read_csv(unique_input_file, sep='\t')
You're doing the same operation for all three dataframes. Instead of duplicating the code, could you maybe create a separate function?

2024-12-06 15:46 UTC, evaklimentova commented on code/excluded_families_testset/unique_family_counter.py
> +   with open(output_path, 'w') as f:
More of a comment than an issue, but with `unique_counts.to_csv(output_path, sep='\t')` you should be able to produce the same file and it might be a bit more efficient.

2024-12-06 16:11 UTC, katarinagresova requested changes

2024-12-06 16:11 UTC, katarinagresova commented on code/excluded_families_testset/README.md
> +* Automatically excludes 'unknown' and '0' family annotations
What does it mean that it "excludes" them?

2024-12-06 16:11 UTC, katarinagresova commented on code/excluded_families_testset/README.md
> +### 2. Family Filter (`exclude_fam.py`)
Can we rename this script? Description is telling me that it will split the data - so something along this line.

2024-12-06 16:11 UTC, katarinagresova commented on code/excluded_families_testset/README.md
> +* File containing families to filter by (from unique_family_counter.py output)
Can you explain how is "File containing families to filter by" used? I guess rows containing ncRNA_fam from this file will be selected for one of the output files - which one?

2024-12-06 16:11 UTC, katarinagresova commented on code/excluded_families_testset/exclude_fam.py
> +    # Read the families file (skipping the 'count' column)
I think this comment is misleading - you are not skipping 'count' column

2024-12-06 16:11 UTC, katarinagresova commented on code/excluded_families_testset/unique_family_counter.py
> +   with open(output_path, 'w') as f:
Yes, this is confusing. It there a reason to save it like this, and not using `to_csv()`? If not, please use `to_csv()`

2024-12-06 17:05 UTC, dimostzim reviewed
addressed everything

2024-12-06 17:18 UTC, katarinagresova commented on code/excluded_families_testset/README.md
> +* File containing families to filter by. This file contains all families that are unique the original dataset compared to other datasets. It is the output of unique_family_counter.py. The noncodingRN
If possible, I would still rewrite this a little, something like:

File containing families to filter by. The noncodingRNA_fam values of this file will be selected and removed from the original file into a new dataset (see excluded dataset output). The remaining original dataset after this removal will be saved (see remaining dataset output)

2024-12-06 17:18 UTC, katarinagresova commented on code/excluded_families_testset/README.md
> +  --leftout leftout_dataset.tsv
I think we call this "remaining dataset" now

2024-12-06 17:18 UTC, katarinagresova commented on code/excluded_families_testset/README.md
> +python exclude_fam.py \
script was renamed

2024-12-06 17:18 UTC, katarinagresova commented on code/excluded_families_testset/unique_family_counter.py
> +def read_and_filter_df(file_path):
Can you change this function to something like `get_unique_fams()` and it would also include `families1 = set(df1['noncodingRNA_fam'].unique())` step ?

2024-12-06 17:18 UTC, katarinagresova commented on code/excluded_families_testset/unique_family_counter.py
> +    unique_counts = df1[df1['noncodingRNA_fam'].isin(unique_to_1)]['noncodingRNA_fam'].value_counts()
Do we need counts of unique family members? Or do we need only their names on the followup analysis?

2024-12-06 17:18 UTC, katarinagresova commented on code/excluded_families_testset/dataset_split_based_on_unique_families.py
> +    unique_families = set(families_df['noncodingRNA_fam'])
Shouldn't they be already unique?
But no harm in making sure.

2024-12-06 17:57 UTC, katarinagresova commented on code/excluded_families_testset/unique_family_counter.py
> +    unique_counts = df1[df1['noncodingRNA_fam'].isin(unique_to_1)]['noncodingRNA_fam'].value_counts()
I don't see the change in this part of the script after latest commits.

2024-12-06 18:06 UTC, dimostzim commented on code/excluded_families_testset/unique_family_counter.py
> +    unique_counts = df1[df1['noncodingRNA_fam'].isin(unique_to_1)]['noncodingRNA_fam'].value_counts()
Sorry, I was meaning to write "not removed". I feel these counts are useful to be part of the output, since it helped me to know how many entries will be removed etc. might also be useful for the user. It helped track how big the final excluded dataset will be.

2024-12-06 18:13 UTC, katarinagresova commented on code/excluded_families_testset/unique_family_counter.py
> +    unique_counts = df1[df1['noncodingRNA_fam'].isin(unique_to_1)]['noncodingRNA_fam'].value_counts()
Thats for the explanations. Makes sense!

2024-12-10 09:06 UTC, evaklimentova approved these changes

2024-12-10 09:39 UTC, stephaniesamm approved these changes

2024-12-11 12:18 UTC, merged