Clustering
BioGeMT/miRBench_paper pull request #46
Opened 2024-12-06 12:59 UTC by dimostzim

Scripts to cluster gene sequeneces and add cluster IDs to original dataset.

2024-12-06 16:26 UTC, katarinagresova requested changes

2024-12-06 16:26 UTC, katarinagresova commented on code/clustering/README.md
Is it possible to include example files?

2024-12-06 16:26 UTC, katarinagresova commented on code/clustering/clustering.R
> +file_path <- "genes.fasta"
This should be input parameter

2024-12-06 16:26 UTC, katarinagresova commented on code/clustering/clustering.R
> +write.csv(clusters, file = "clusters_cutoff_0.1.csv")
This should be input parameter.

2024-12-06 16:26 UTC, katarinagresova commented on code/clustering/clustering.R
Modify this script so it can be run from command line and will accept command line arguments

2024-12-06 16:26 UTC, katarinagresova commented on code/clustering/gene_fasta.py
> +            fasta_file.write(f">Seq_{index + 1}\n{sequence}\n")
Why adding `1` to index?

2024-12-06 16:26 UTC, katarinagresova commented on code/clustering/map_gene_clusters.py
> +def load_clusters(cluster_csv):
Why do you need to do this complicated loading? You should know how you saved the file you are loading in here.

2024-12-06 16:26 UTC, katarinagresova commented on code/clustering/map_gene_clusters.py
> +    parser.add_argument("--gene_tsv", required=True, help="TSV file containing gene data")
From the description it is not clear to me what it this `--gene_tsv` file. Is it the dataset file as is being processed though our post process pipeline?

2024-12-06 16:26 UTC, katarinagresova commented on code/clustering/map_gene_clusters.py
> +    gene_column = detect_sequence_column(gene_df, seq_clusters_df["Sequence"].values)
You should know name of the gene column. Or maybe it can be input parameter. What is the reason to detect it like this?

2024-12-06 16:26 UTC, katarinagresova commented on code/clustering/map_gene_clusters.py
> +    parser.add_argument("--fasta_file", required=True, help="Input FASTA file with gene sequences")
Why to you need fasta file here? You have Gene ID in cluster_csv - just parse it from seq_id

2024-12-06 16:26 UTC, katarinagresova commented on code/clustering/map_gene_clusters.py
> +    gene_df["ClusterID"] = gene_df[gene_column].map(sequence_to_cluster).fillna("NA")
I would use a better name of the column. Something like `gene_cluster_ID` or something - to make it clear that is is connected to `gene`

2024-12-09 16:04 UTC, katarinagresova commented on code/clustering/map_gene_clusters.py
> +    parser.add_argument("--fasta_file", required=True, help="Input FASTA file with gene sequences")
Yes, I was thinking about using the order, since you are creating Seq_id from the order. 
Are gene sequences unique? Can we even use them as index?

2024-12-09 16:48 UTC, dimostzim commented on code/clustering/map_gene_clusters.py
> +    parser.add_argument("--fasta_file", required=True, help="Input FASTA file with gene sequences")
gene sequences might not necessarily be unique. removed the fasta function and we now add cluster IDs based on order

2024-12-10 08:50 UTC, evaklimentova commented on code/clustering/map_gene_clusters.py
> +    return dict(zip(clusters_df["Seq_ID"], clusters_df["Cluster_ID"]))
I'm really worried about the way you treat the cluster IDs. I'm afraid that making a dictionary and then pulling values from there will not preserve the original order and make a random sorting. 
And if I'm reading the code correctly, you're not using the `Seq_ID` anywhere, so what about just reading the `Cluster_ID` column and stitching it to the `gene_df`? Or if you're not sure about the order in `cluster_csv`, use the `Seq_ID` to merge it with the `gene_df` (on its index)

2024-12-10 09:51 UTC, dimostzim commented on code/clustering/clustering.R
> +names(clusters_df)[2] <- "Cluster_ID"
Yes. For some reason in R it keeps the original "clusters" name if we do not explicitly override this. If we remove this renaming, the final csv has "clusters" column.

2024-12-10 10:01 UTC, evaklimentova commented on code/clustering/clustering.R
> +names(clusters_df)[2] <- "Cluster_ID"
Ok, interesting, thanks for explaining :)

2024-12-10 10:12 UTC, dimostzim commented on code/clustering/map_gene_clusters.py
> +    return dict(zip(clusters_df["Seq_ID"], clusters_df["Cluster_ID"]))
We are sure about the order, because we know how the .fasta file with Seq_IDs was created. We now simply read both files, create a new column  "gene_cluster_ID" in the gene dataFrame and fill it with he "Cluster_ID" column of the clusters dataFrame.

2024-12-10 13:57 UTC, evaklimentova approved these changes

2024-12-11 12:17 UTC, stephaniesamm approved these changes

2024-12-11 12:40 UTC, merged